### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by gedw99** [plgd-dev/plgd.mobile#2]
This is quite a nice example.m of the potential of the system.

I wonder if wasm might work for flutter web !!

**Comment by ondrejtomcik** [comment]
Hello @gedw99!

Thank you for your question. Sorry for the delay, the application was not yet finalised. At this moment, it's available for both, Android and iOS platforms - you can download it in the appstore. Search for 'plgd.dev'. 

Regarding flutter web, I doubt it would work, as we are using native libraries. The https://github.com/plgd-dev/sdk is compiled using gomobile and imported as a native module.

If you have any ideas, please feel free to write them here.

Ondrej
